### ISSUE TITLE
Question: Tracer vs logger

### ISSUE THREAD

**Issue by gianarb** [thoas/bokchoy#11]
Hello!

My focus atm is on instrumentation, I wrote my logger and my tracer using zap. It is kind of working I think, but I do not understand the difference. Looking at the Tracer and how it is used in `queue.go` it logs and that's it. I would like to do a trace such as OpenTracing, OpenTeletry. Do you have any suggestions? I think I can do a mix of middleware/event but I would like to get a direction from you.

Thanks a lot

**Comment by thoas** [comment]
Sorry for the late reply, the `Tracer` is only responsible to report errors (think [sentry](https://github.com/thoas/bokchoy/blob/master/contrib/sentry/sentry.go)) and the logger is an internal component to log internal events of bokchoy.

You can disable the internal logger and keep the tracer, that's why there are completely different components.

I hope I answered your question, don't hesitate if it's not the case.

**Comment by gianarb** [comment]
Thanks for the explanation.
Do you have any suggestion about how I can/should instrument this library with opentracing or similar?! Thanks
